#!/bin/bash

# Change config file path
export KRB5_CONFIG=/kerberos/krb5.conf
export KRB5_KDC_PROFILE=/kerberos/krb5kdc/kdc.conf

# 
#KADMIN_PRINCIPAL_LONG=$KADMIN_PRINCIPAL@$REALM

# Print configuration variables
echo "Starting Kerberos server"
echo ""
echo "    Realm:                    $REALM"
echo "    Encryption Types:         $SUPPORTED_ENCRYPTION_TYPES"
echo "    kAdmin principal:         $KADMIN_PRINCIPAL"
echo "    kAdmin password:          $KADMIN_PASSWORD"
echo "    KDC hostname:             $KDC_HOSTNAME"
echo ""

# Create config folder
if [ ! -d /kerberos/krb5kdc ]; then
    mkdir /kerberos/krb5kdc
    chmod 755 /kerberos/krb5kdc
fi

# Create krb5.conf
if [ ! -f /kerberos/krb5.conf ]; then
    echo "[libdefaults]
	default_realm = $REALM
[realms]
	$REALM = {
		kdc = $KDC_HOSTNAME
		admin_server = $KDC_HOSTNAME
        default_domain = ${KDC_HOSTNAME,,}
        kdc_ports = 88,750
		kadmind_port = 749
	}" > /kerberos/krb5.conf
fi

# Create kdc.conf
if [ ! -f /kerberos/krb5kdc/kdc.conf ]; then
    echo "[realms]
	$REALM = {
        database_name = /kerberos/krb5kdc/principal
        admin_keytab = FILE:/kerberos/krb5kdc/kadm5.keytab
        acl_file = /kerberos/krb5kdc/kadm5.acl
        key_stash_file = /kerberos/krb5kdc/stash
        kdc_ports = 88,750
        max_life = 12h 0m 0s
		max_renewable_life = 14d 0h 0m 0s
		supported_enctypes = $SUPPORTED_ENCRYPTION_TYPES
		default_principal_flags = +preauth
	}" > /kerberos/krb5kdc/kdc.conf
fi

# Create ACL file
if [ ! -f /kerberos/krb5kdc/kadm5.acl ]; then
    echo "$KADMIN_PRINCIPAL@$REALM *" > /kerberos/krb5kdc/kadm5.acl
fi

if [ ! -f /kerberos/krb5kdc/stash ]; then
    DB_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    echo "    Database Master Password: $DB_PASSWORD"
    echo ""
    kdb5_util create -s <<EOF
$DB_PASSWORD
$DB_PASSWORD
EOF
fi

# Change password
kadmin.local -q "delete_principal -force $KADMIN_PRINCIPAL@$REALM"
kadmin.local -q "add_principal -pw $KADMIN_PASSWORD $KADMIN_PRINCIPAL@$REALM"

krb5kdc
kadmind -nofork